### ISSUE TITLE
Libra Intergration

### ISSUE THREAD

**Issue by mw2000** [Blockchain-at-Davis/BaD-DDE#1]
Would love to see support for the Libra Blockchain in the BaD Dapp Dev Environment!

**Comment by johnzl-777** [comment]
Libra support is underway. There are a number of build-time issues that present themselves because of how much `rustc` needs in terms of memory.

I'm slowly increasing the amount of RAM to the VM to see what the ideal amount is

**Comment by johnzl-777** [comment]
Due to the large system requirements that Libra requires and its one-time usage for a workshop around winter quarter, I have opted to not include the Libra environment in DDE.

In the future, there may be a way to precompile the Libra libraries and distribute it with the image itself over Docker or some other means that doesn't require the large RAM requirement.
